//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lmbrd
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sdacha
    {
        public int SdachaID { get; set; }
        public string Category { get; set; }
        public int IDClienta { get; set; }
        public string Opisanie { get; set; }
        public System.DateTime Date_sdachi { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> Komissia { get; set; }
        public Nullable<System.DateTime> Date_vozvrata_p { get; set; }
        public Nullable<System.DateTime> Date_vozvrata_f { get; set; }
    
        public virtual Category Category1 { get; set; }
        public virtual Klienti Klienti { get; set; }
    }
}
